"""
This is a test file that is mostly written by AI. It is just used for experimenting and testing.
It is fully slop code that does not hold any value just used for testing. For example, currently I'm testing here to get thinking and other things from local llms.
Some part are handwritten but most of the code is generated by AI. It is not used in production and it is not used in any important place. It is just used for testing and experimenting and prototyping.
"""
"""Local chat helper for Qwen3.5-2B-Q4_K_M.gguf."""

import argparse
import os
import sys
from pathlib import Path

from introlix.config import MODEL_SAVE_DIR
from introlix.services.LLMState import LLMState
from introlix.prompts import chat_agent_prompt
from introlix.tools.tool_def import SEARCH_TOOL_DEF, FAST_SEARCH_TOOL_DEF

tools = [SEARCH_TOOL_DEF, FAST_SEARCH_TOOL_DEF]

DEFAULT_MODEL_NAME = "Qwen3-4B-Thinking-2507-Q4_K_M.gguf"

LOCAL_LLM_STATE = LLMState()

MODEL_SEARCH_PATHS = [
    Path.cwd(),
    Path.home(),
    Path.home() / "models",
    Path.home() / ".local" / "share" / "introlix" / "models",
    MODEL_SAVE_DIR,
]


def find_local_model(model_path: str) -> Path:
    candidate = Path(os.path.expanduser(model_path))
    if candidate.is_file():
        return candidate.resolve()

    if candidate.is_dir():
        raise FileNotFoundError(f"Specified model path is a directory: {candidate}")

    # try direct relative/absolute paths first
    if candidate.exists():
        return candidate.resolve()

    # if user passed just a filename, search known locations
    for base in MODEL_SEARCH_PATHS:
        test_path = (base / model_path).expanduser().resolve()
        if test_path.is_file():
            return test_path

    raise FileNotFoundError(
        f"Model file not found: {model_path}\n"
        f"Tried current directory, home, ~/models, ~/.local/share/introlix/models, /usr/local/share/models, /usr/share/models."
    )


def create_model(model_path: Path, n_ctx: int, n_gpu_layers: int):
    try:
        from llama_cpp import Llama
    except ImportError as exc:
        raise RuntimeError(
            "llama-cpp-python is not installed. Install it with 'pip install llama-cpp-python'"
        ) from exc

    print(f"Loading model from: {model_path}")
    llm = Llama(
        model_path=str(model_path),
        n_ctx=n_ctx,
        n_gpu_layers=n_gpu_layers,
    )
    LOCAL_LLM_STATE.llm = llm
    LOCAL_LLM_STATE.current_model_name = str(model_path)
    print("Model loaded successfully.")
    return llm


def build_prompt(
    system_prompt: str, history: list[tuple[str, str]], user_text: str
) -> str:
    messages = []
    if system_prompt:
        messages.append({"role": "system", "content": system_prompt})
    for role, content in history:
        messages.append({"role": role, "content": content})
    messages.append({"role": "user", "content": user_text})
    return messages


def chat_loop(llm_state: LLMState, system_prompt: str):
    print("\nLocal agent chat loop ready. Type a message and press Enter.")
    print("Submit an empty line to exit.\n")

    # Maintain standard OpenAI format for native chat template routing
    messages = []
    if system_prompt:
        messages.append({"role": "system", "content": system_prompt})

    while True:
        try:
            user_input = input("You: ").strip()
        except (KeyboardInterrupt, EOFError):
            print("\nExiting chat.")
            break

        if not user_input:
            print("Exiting chat.")
            break

        # Append new input directly to the structural dictionary array
        messages.append({"role": "user", "content": user_input})

        try:
            # Native endpoint with streaming and schema grammars activated
            response_stream = llm_state.llm.create_chat_completion(
                messages=messages,
                temperature=0.1,    # Low temperature prevents structural JSON breakages
                max_tokens=512,
                tools=tools,        # Your tools array variable
                tool_choice="auto",
                stream=True
            )
        except Exception as exc:
            print(f"Error generating response: {exc}")
            break

        print("Assistant: ", end="", flush=True)
        
        full_text_response = ""
        tool_calls_buffer = {}

        # Parse the live stream delta chunks
        for chunk in response_stream:
            delta = chunk["choices"][0]["delta"]

            if "reasoning_content" in delta and delta["reasoning_content"]:
                print(f"Reasoning: {delta['reasoning_content']}", end="", flush=True)

            if "content" in delta and delta["content"]:
                text_chunk = delta["content"]
                print(text_chunk, end="", flush=True)
                full_text_response += text_chunk

            # 2. Handle structural tool call parameter streaming
            if "tool_calls" in delta:
                for tool_call in delta["tool_calls"]:
                    index = tool_call["index"]
                    
                    if index not in tool_calls_buffer:
                        tool_calls_buffer[index] = {
                            "id": tool_call.get("id", ""),
                            "name": tool_call.get("function", {}).get("name", ""),
                            "arguments": ""
                        }
                    
                    argument_chunk = tool_call.get("function", {}).get("arguments", "")
                    tool_calls_buffer[index]["arguments"] += argument_chunk

        print("\n") # Newline after streaming finishes

        # Process and append results to history arrays
        if tool_calls_buffer:
            # Format tool requirements back to messages history array
            assistant_tool_message = {
                "role": "assistant",
                "tool_calls": [
                    {
                        "id": call["id"],
                        "type": "function",
                        "function": {"name": call["name"], "arguments": call["arguments"]}
                    } for call in tool_calls_buffer.values()
                ]
            }
            messages.append(assistant_tool_message)
            
            # Execute your local application functions here
            for index, call in tool_calls_buffer.items():
                print(f"[Executing Tool] Function: {call['name']} | Args: {call['arguments']}")
                
                # --- EXECUTE YOUR LOCAL TOOL LOGIC HERE AND GET AN ANSWER ---
                # tool_result = execute_local_function(call['name'], call['arguments'])
                # messages.append({"role": "tool", "tool_call_id": call["id"], "content": str(tool_result)})
                
        else:
            # Standard text update to history array
            messages.append({"role": "assistant", "content": full_text_response})

        # Keep context history capped to prevent infinite memory growth
        # 12 items retains roughly 4-5 full conversation turns
        if len(messages) > 12:
            # Retain system prompt at index 0 if it exists
            offset = 1 if system_prompt else 0
            messages = ([messages[0]] if offset else []) + messages[-11:]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Load a local Qwen GGUF model and chat with it from the terminal."
    )
    parser.add_argument(
        "--model",
        "-m",
        default=DEFAULT_MODEL_NAME,
        help=(
            "Path to the local GGUF model file or model filename to search for in known locations. "
            f"Default: {DEFAULT_MODEL_NAME}"
        ),
    )
    parser.add_argument(
        "--n-ctx",
        type=int,
        default=2048,
        help="Context window size. Default: 2048.",
    )
    parser.add_argument(
        "--n-gpu-layers",
        type=int,
        default=0,
        help="Number of layers to offload to GPU via llama.cpp. Default: 0 (CPU only).",
    )
    parser.add_argument(
        "--system",
        type=str,
        default="",
        help="Optional system prompt to guide the model's behavior.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    try:
        model_path = find_local_model(args.model)
    except FileNotFoundError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    try:
        create_model(model_path, args.n_ctx, args.n_gpu_layers)
    except Exception as exc:
        print(f"Error loading model: {exc}", file=sys.stderr)
        return 2

    chat_loop(LOCAL_LLM_STATE, chat_agent_prompt)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
